export default [
  {
    img: "./img/image1.jpg",
    year: 2019,
    model: "Volkswagen Tiguan",
    mileage: 19.855,
    box: "Automatic",
    engine: "Diesel",
    price: 34.888,
  },
  {
    img: "./img/image2.jpg",
    year: 2014,
    model: "Toyota Highlander XLE",
    mileage: 69.0,
    box: "Automatic",
    engine: "Gas",
    price: 27.875,
  },
  {
    img: "./img/image3.jpg",
    year: 2017,
    model: "Lexus RX 350 LUXURY",
    mileage: 39.85,
    box: "Automatic",
    engine: "Gas",
    price: 38.775,
  },
  {
    img: "./img/image4.jpg",
    year: 2016,
    model: "Toyota Highlander LE A...",
    mileage: 104.0,
    box: "Automatic",
    engine: "Diesel",
    price: 23.728,
  },
  {
    img: "./img/image5.jpg",
    year: 2017,
    model: "Hyundai Elantra",
    mileage: 95.0,
    box: "Automatic",
    engine: "Gas",
    price: 11.788,
  },
  {
    img: "./img/image6.jpg",
    year: 2016,
    model: "Mercedes-Benz GLE-Cl...",
    mileage: 59.8,
    box: "Automatic",
    engine: "Diesel",
    price: 38.878,
  },
  {
    img: "./img/image7.jpg",
    year: 2015,
    model: "Toyota Venza AWD XLE...",
    mileage: 99.0,
    box: "Automatic",
    engine: "Gas",
    price: 18.62,
  },
  {
    img: "./img/image8.jpg",
    year: 2016,
    model: "Lexus RX 350 F-SPORT",
    mileage: 86.0,
    box: "Automatic",
    engine: "Gas",
    price: 34.888,
  },
  {
    img: "./img/image9.jpg",
    year: 2017,
    model: "Hyundai Elantra",
    mileage: 95.0,
    box: "Automatic",
    engine: "Gas",
    price: 11.788,
  },
  {
    img: "./img/image10.jpg",
    year: 2017,
    model: "Hyundai Elantra",
    mileage: 95.0,
    box: "Automatic",
    engine: "Gas",
    price: 11.788,
  },
  {
    img: "./img/image11.jpg",
    year: 2017,
    model: "Hyundai Elantra",
    mileage: 95.0,
    box: "Automatic",
    engine: "Gas",
    price: 11.788,
  },
  {
    img: "./img/image12.jpg",
    year: 2017,
    model: "Hyundai Elantra",
    mileage: 95.0,
    box: "Automatic",
    engine: "Gas",
    price: 11.788,
  },
  {
    img: "./img/image5.jpg",
    year: 2017,
    model: "Hyundai Elantra",
    mileage: 95.0,
    box: "Automatic",
    engine: "Gas",
    price: 11.788,
  },
  {
    img: "./img/image5.jpg",
    year: 2017,
    model: "Hyundai Elantra",
    mileage: 95.0,
    box: "Automatic",
    engine: "Gas",
    price: 11.788,
  },
  {
    img: "./img/image5.jpg",
    year: 2017,
    model: "Hyundai Elantra",
    mileage: 95.0,
    box: "Automatic",
    engine: "Gas",
    price: 11.788,
  },
  {
    img: "./img/image5.jpg",
    year: 2017,
    model: "Hyundai Elantra",
    mileage: 95.0,
    box: "Automatic",
    engine: "Gas",
    price: 11.788,
  },
  {
    img: "./img/image5.jpg",
    year: 2017,
    model: "Hyundai Elantra",
    mileage: 95.0,
    box: "Automatic",
    engine: "Gas",
    price: 11.788,
  },
  {
    img: "./img/image5.jpg",
    year: 2017,
    model: "Hyundai Elantra",
    mileage: 95.0,
    box: "Automatic",
    engine: "Gas",
    price: 11.788,
  },
  {
    img: "./img/image5.jpg",
    year: 2017,
    model: "Hyundai Elantra",
    mileage: 95.0,
    box: "Automatic",
    engine: "Gas",
    price: 11.788,
  },
  {
    img: "./img/image5.jpg",
    year: 2017,
    model: "Hyundai Elantra",
    mileage: 95.0,
    box: "Automatic",
    engine: "Gas",
    price: 11.788,
  },
  {
    img: "./img/image5.jpg",
    year: 2017,
    model: "Hyundai Elantra",
    mileage: 95.0,
    box: "Automatic",
    engine: "Gas",
    price: 11.788,
  },
  {
    img: "./img/image5.jpg",
    year: 2017,
    model: "Hyundai Elantra",
    mileage: 95.0,
    box: "Automatic",
    engine: "Gas",
    price: 11.788,
  },
];
